In [1]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np

In [2]:
model_df = pd.read_csv("../data/model.csv")
model_df.loc[model_df.FL_DATE == "5/3/2018"]

,AIRPORT_ID,YEAR,MONTH,DAY_OF_MONTH,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,...,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,field1,FL_DATE.1,DurationofEvent
3483,18205,2018,5,3,5/3/2018,AA,19805,AA,N969AN,55,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
3532,18254,2018,5,3,5/3/2018,AA,19805,AA,N936NN,168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
3550,18272,2018,5,3,5/3/2018,AA,19805,AA,N907NN,220,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
3569,18291,2018,5,3,5/3/2018,AA,19805,AA,N959AN,1554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
3576,18298,2018,5,3,5/3/2018,AA,19805,AA,N996AN,1569,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4877,23128,2018,5,3,5/3/2018,AA,19805,AA,N903AA,2234,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
4892,23143,2018,5,3,5/3/2018,AA,19805,AA,N823NN,2239,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
4903,23154,2018,5,3,5/3/2018,AA,19805,AA,N883NN,2270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
4913,23164,2018,5,3,5/3/2018,AA,19805,AA,N921AN,2279,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000
4921,23172,2018,5,3,5/3/2018,AA,19805,AA,N906AN,2283,...,1842.0,81.0,81.0,NaN,NaN,NaN,NaN,3.0,5/3/2018,0 days 21:42:00.000000000

In [3]:
model_df = model_df[["FL_DATE", "WEATHER_DELAY", "DurationofEvent"]]
model_df.head(50)

      FL_DATE  WEATHER_DELAY            DurationofEvent
0    1/2/2018           43.0                        NaN
1    1/6/2018           22.0                        NaN
2   1/13/2018            0.0                        NaN
3   1/15/2018           23.0                        NaN
4   1/29/2018            0.0                        NaN
5    1/5/2018            0.0                        NaN
6    1/7/2018            7.0                        NaN
7    1/8/2018            0.0                        NaN
8   1/12/2018            0.0                        NaN
9   1/15/2018           16.0                        NaN
10  1/19/2018            0.0                        NaN
11  1/21/2018            0.0                        NaN
12  1/26/2018            0.0                        NaN
13   1/2/2018           27.0                        NaN
14   1/1/2018            0.0                        NaN
15   1/5/2018            0.0                        NaN
16   1/8/2018            0.0                        NaN
17  1/10/2018            0.0                        NaN
18  1/11/2018            0.0                        NaN
19  1/12/2018            0.0                        NaN
20  1/14/2018            1.0                        NaN
21  1/15/2018            2.0                        NaN
22  1/17/2018            0.0                        NaN
23  1/21/2018            0.0                        NaN
24  1/22/2018            0.0  0 days 00:32:00.000000000
25  1/24/2018            0.0                        NaN
26  1/25/2018            0.0                        NaN
27  1/26/2018            0.0                        NaN
28  1/28/2018            0.0                        NaN
29  1/29/2018            0.0                        NaN
30  1/31/2018            0.0                        NaN
31   1/1/2018            0.0                        NaN
32   1/7/2018            9.0                        NaN
33  1/11/2018            0.0                        NaN
34  1/12/2018            9.0                        NaN
35  1/15/2018            5.0                        NaN
36   1/2/2018           19.0                        NaN
37   1/2/2018            0.0                        NaN
38  1/11/2018            0.0                        NaN
39  1/21/2018            0.0                        NaN
40  1/22/2018            0.0  0 days 00:32:00.000000000
41   1/6/2018            0.0                        NaN
42   1/7/2018            9.0                        NaN
43  1/14/2018           25.0                        NaN
44  1/15/2018           35.0                        NaN
45  1/28/2018           14.0                        NaN
46   1/2/2018            0.0                        NaN
47   1/7/2018           11.0                        NaN
48  1/10/2018            0.0                        NaN
49  1/12/2018            0.0                        NaN

In [11]:
event_df = model_df["DurationofEvent"].tolist()
event_df

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:32:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:18:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:18:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 '0 days 00:18:00.000000000',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...]

In [15]:
event_df = [0 if x != x else x for x in event_df]
event_df

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 '0 days 00:32:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:18:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 '0 days 00:18:00.000000000',
 0,
 0,
 0,
 0,
 0,
 '0 days 00:18:00.000000000',
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [16]:
model_df["DurationofEvent"] = event_df
model_df

          FL_DATE  WEATHER_DELAY DurationofEvent
0        1/2/2018           43.0               0
1        1/6/2018           22.0               0
2       1/13/2018            0.0               0
3       1/15/2018           23.0               0
4       1/29/2018            0.0               0
...           ...            ...             ...
14389  12/20/2018            NaN               0
14390  12/27/2018            NaN               0
14391  12/28/2018            NaN               0
14392  12/29/2018            NaN               0
14393  12/31/2018            NaN               0

[14394 rows x 3 columns]

In [23]:
clean_model = model_df.dropna()
clean_model

          FL_DATE  WEATHER_DELAY LENGTH_OF_THUNDERSTORM
0        1/2/2018           43.0                      0
1        1/6/2018           22.0                      0
2       1/13/2018            0.0                      0
3       1/15/2018           23.0                      0
4       1/29/2018            0.0                      0
...           ...            ...                    ...
14213   12/9/2018          710.0                      0
14233   12/5/2018         1840.0                      0
14274   12/7/2018         1034.0                      0
14280  12/20/2018          900.0                      0
14305  12/16/2018          653.0                      0

[1193 rows x 3 columns]

In [20]:
clean_model.rename(columns={"DurationofEvent": "LENGTH_OF_THUNDERSTORM"},inplace=True)

In [24]:
clean_model

          FL_DATE  WEATHER_DELAY LENGTH_OF_THUNDERSTORM
0        1/2/2018           43.0                      0
1        1/6/2018           22.0                      0
2       1/13/2018            0.0                      0
3       1/15/2018           23.0                      0
4       1/29/2018            0.0                      0
...           ...            ...                    ...
14213   12/9/2018          710.0                      0
14233   12/5/2018         1840.0                      0
14274   12/7/2018         1034.0                      0
14280  12/20/2018          900.0                      0
14305  12/16/2018          653.0                      0

[1193 rows x 3 columns]